#cloud-config
users:
  - default
  - name: rages
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPVbB5cWrB+F9Moy1Ic0O83+Jydgn49/K7bvDQtmJhRl rages@Acacia
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4sO8y0r1fbE2nY2hwlpAlxdtWrUunX8FRPeKmn1yajVFtqbBOrMdv895rxQxC7g5t3grXihIppv3wD4IR6kp8WWUrtHLzlf/wVNx+PtH+WLLXxOsbztOFuvpinwB562DyiPD127XyU9gHGvcUio4zfySmmTuLXElpaPa05QVrVOpaBU3P7fphv5vJ1kxUZXzr7kpqN48jr6rwfld/NL7fBFsbIqV16wR0OiOoIk4Hn2V0YARJypFNhMSFhUQG+NQg6gVlyxvciDVkrJrPsJz9YJunEoIPLDGbYe1+nW/CzgrWlFcH0nzJfwfGBjDa5MNZPWI6TswzUWZJTK4sG98ZWIUoHytlFMY1Nill8SEqV0zLvzOk2RgnKAGEd9IEFXA+SyBNAn3NORfWfmhmNSZO3oMmzDdKUV2L2F+k4u33QttxPYXigeVzEi2sxK/LRnHgNAMTMLX/xva2m7wYsAWtjBDs7Z+YccQAA77yiXVamxDToa6x428dH3MLgxy52L0= rages@Euphorbia
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: [adm, cdrom, dip, lxd, sudo]
    shell: /bin/bash
    homedir: /home/rages

# package_update: true
# package_upgrade: true

runcmd:
  - mkdir -p /tmp/init/dotfiles
  - git clone https://github.com/rageshkrishna/dotfiles.git /tmp/init/dotfiles
  - sudo su rages -c "pushd /tmp/init/dotfiles && ./setup-vim.sh && popd"
  - |
    cat > /home/rages/.tmux.conf <<EOF
    set -g mouse "on"
    set -g default-terminal "screen-256color"
    EOF
